### ISSUE TITLE
v3.5.8 does not work (req.resolve is not a function)

### ISSUE THREAD

**Issue by NTICompass** [Roman86/tailwindcss-scoped-preflight#69]
**Describe the bug**
After updating from 3.5.7 to 3.5.8, I get an error when running `vite` as a dev server.

```
3:45:01 PM [vite] Internal server error: [postcss] req.resolve is not a function
  Plugin: vite:css
  File: /home/nticompass/Code/project/src/styles.css?direct:undefined:NaN
      at file:///home/nticompass/Code/project/node_modules/tailwindcss-scoped-preflight/dist/index.js:87:29
      at registerPlugins (/home/nticompass/Code/project/node_modules/tailwindcss/lib/lib/setupContextUtils.js:815:61)
      at createContext (/home/nticompass/Code/project/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1221:5)
      at getContext (/home/nticompass/Code/project/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1278:19)
      at /home/nticompass/Code/project/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:121:81
      at /home/nticompass/Code/project/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
      at plugins (/home/nticompass/Code/project/node_modules/tailwindcss/lib/plugin.js:38:69)
      at LazyResult.runOnRoot (/home/nticompass/Code/project/node_modules/postcss/lib/lazy-result.js:361:16)
      at LazyResult.runAsync (/home/nticompass/Code/project/node_modules/postcss/lib/lazy-result.js:290:26)
      at async runPostCSS (file:///home/nticompass/Code/project/node_modules/vite/dist/node/chunks/node.js:20913:19)
```

My `styles.css` is simply (with CSS in the `@layer` blocks):

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {}
@layer components {}
@layer utilities {}
```

My `tailwind.config.mjs` contains:

```
scopedPreflightStyles({
    isolationStrategy: isolateInsideOfContainer('.use-tw', {
        except: '.no-tw',
    }),
}),
```

**To Reproduce**
Run `vite` as a dev server and it immediately crashes when you try to load https://localhost:5173/

**Expected behaviour**
`vite` (and `postcss`) work and I can access  https://localhost:5173/

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 148.0.2

**Smartphone (please complete the following information):**
Irrelevant

**Additional context**
vite: 8.0.0
tailwindcss: 3.4.17
postcss-cli: 11.0.1

Note that everything works fine in v3.5.7.

**Comment by Roman86** [comment]
looking into it

**Comment by Roman86** [comment]
@NTICompass could you please check if v3.5.9 works for you? I added some tests covering your case, should help.

**Comment by NTICompass** [comment]
@Roman86 I installed v3.5.9 and it seems to be working!  Thank you :-)
